### ISSUE TITLE
Completed uploads are kept in the TusURLStore when resuming is enabled

### ISSUE THREAD

**Issue by jjrodrig** [tus/tus-java-client#26]
```remove(String fingerprint)``` is never called for *TusURLStore* after a completed upload

The upload fingerprints are kept at the TusURLStore, this coul be a problem if a persistent URLStore is used as in the Android client where the PreferencesStore is used with this purpose. 

Which is the expected behaviour? Should'nt be removed from the URLStore?

**Comment by Acconut** [comment]
> Which is the expected behaviour?

Yes, this is the currently expected behavior. tus-java-client does not remove fingerprints at the moment and it would be the task of the library user to take care of cleaning up the URL storage.

> Should'nt be removed from the URLStore?

There are situations in which the URLs should be cleaned up after the upload is finished and there are other situations where this should not happen. That's why tus-js-client, for example, has the `removeFingerprintOnSuccess` option (see https://github.com/tus/tus-js-client/#tusdefaultoptions) which removes the entry for the URL storage. tus-java-client has no comparable option but we are happy to accept a PR for that feature!

**Comment by Acconut** [comment]
This feature has been implemented in #27
